version: '2.1'

orbs:
  linear-release: mishchief/linear-release@0.1.3

jobs:
  hello:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "hello"

workflows:
  deploy:
    jobs:
      - hello
      - linear-release/deploy:
          context: linear-release-prod
          filters:
            branches:
              only: main
          name: sync-linear-release
